[[mgr.prepend_keymap]]
on = "t"
run = "toggle"
desc = "Toggle the current selection state"

[[mgr.prepend_keymap]]
on = "T"
run = [
    "toggle",
    "arrow next",
]
desc = "Toggle the current selection state"

[[mgr.prepend_keymap]]
on = "o"
run = "create"
desc = "Create a file (ends with / for directories)"

[[mgr.prepend_keymap]]
on = [
    "y",
    "c",
]
run = '''shell -- nu -c "notify-send hi '$@'"'''
desc = "Copy the file contents"

[[mgr.prepend_keymap]]
on = [
    "y",
    "d",
]
run = "copy dirname"
desc = "Copy the directory path"

[[mgr.prepend_keymap]]
on = [
    "y",
    "f",
]
run = "copy filename"
desc = "Copy the filename"

[[mgr.prepend_keymap]]
on = [
    "y",
    "n",
]
run = "copy name_without_ext"
desc = "Copy the filename without extension"

[[mgr.prepend_keymap]]
on = [
    "y",
    "p",
]
run = "copy path"
desc = "Copy the file path"

[[mgr.prepend_keymap]]
on = [
    "y",
    "y",
]
run = "yank"
desc = "Yank selected files (copy)"

[[mgr.prepend_keymap]]
on = [
    "d",
    "D",
]
run = "remove --permanently"
desc = "Permanently delete selected files"

[[mgr.prepend_keymap]]
on = [
    "d",
    "d",
]
run = "yank --cut"
desc = "Yank selected files (cut)"

[[mgr.prepend_keymap]]
on = [
    "d",
    "t",
]
run = "remove"
desc = "Trash selected files"

[[mgr.prepend_keymap]]
on = "A"
run = "rename --cursor=after_ext"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "C"
run = "rename --empty=dot_ext"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "I"
run = "rename --cursor=start"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = [
    "c",
    "c",
]
run = "rename --empty=all"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = [
    "c",
    "e",
]
run = "rename --empty=ext"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = [
    "c",
    "w",
]
run = "rename --empty=stem --cursor=start"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "a"
run = "rename --cursor=before_ext"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "i"
run = "rename --cursor=start"
desc = "Rename selected file(s)"

[[mgr.prepend_keymap]]
on = "<c-t>"
run = "tab_create --current"
desc = "Create a new tab with CWD"

[[mgr.prepend_keymap]]
on = "<a-q>"
run = "close"
desc = "Close the current tab, or quit if it's last"

[[mgr.prepend_keymap]]
on = "<a-p>"
run = "tab_switch -1 --relative"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = "<a-n>"
run = "tab_switch 1 --relative"
desc = "Switch to next tab"

[[mgr.prepend_keymap]]
on = "1"
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "2"
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "3"
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "4"
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "5"
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "6"
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "7"
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "8"
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = "9"
run = "plugin relative-motions 9"
desc = "Move in relative steps"
